### ISSUE TITLE
Error when installing the solution

### ISSUE THREAD

**Issue by CSART** [lestersconyers/ls.widgets#1]
Hi
When I try to install the solution in my DEV Sharepoint farm, I directly receive the error message : 
Échec de l'instanciation du fichier « Style Library/ls.widgets/base/handlebars-helpers.js » à partir du module « Style Library » : la liste spécifiée n'existe pas. 
I'm using a French version, so I translate for you : Error in the instanciation of the file "Style..." from the module "Style Library" : the specified list doesn't exitst.
Is there anything specific to do except deploying the solution ?
Many thanks. Cheers.

**Comment by CSART** [comment]
Just to add some info : the style Library exist (Style%20Library) but the title is in French.

**Comment by lestersconyers** [comment]
Sorry but I don't have any non-english sites to test this on. Can you open your site using SharePoint designer and check out the folder structure? What happens if you attempt to create a folder named "Style Library"?

**Comment by CSART** [comment]
Hi
Thanks for your feedback
As you can see in this screenshot coming from MS Designer (English version), the Style Library/ls.widgets/base folder was created during the solution deployment or activation and is thus existing.
The list is empty.



[cid:image002.png@01D02C25.DD1298E0]

Note however that the full url of my site collection is http://myweb/sites/sitecollection-name
This style library is thus http://myweb/sites/sitecollection-name/Style%20Library/...
Are you sure that your solution doesn’t check in http://myweb/Style%20Library/… ?
I already experienced such behavior with third parties in the past…

Christophe Sarteel

**Comment by lestersconyers** [comment]
No image came through. I don't have any feature activation code or anything. It's using the default declarative provisioning. I wonder if you delete that folder and create a document library named Style Library, it will work. Give that a try.

**Comment by lestersconyers** [comment]
Should be corrected in latest solution.
